### ISSUE TITLE
Does not build on debian

### ISSUE THREAD

**Issue by ghost** [OpenDungeons/OpenDungeons#1323]
My system have the following properties:

* debian 11
* `CXXFLAGS=-g -std=c++14 -Weverything -Wall -Wno-c++98-compat-pedantic -Wno-c++98-compat -Wno-documentation -Wno-documentation-deprecated-sync -Wno-documentation-unknown-command`
* `CCFLAGS= -g -std=c14   -Weverything -Wall -Wno-c99-compat-pedantic   -Wno-c99-compat`
* `CXX=clang++`
* `CC=clang`

Debian 11 embeds:

* cegui-mk2-0.8.7 
* libogre-1.12-dev
* libsfml-dev (2.5.1+dfsg-1)
* libois-1.3.0v5

Maybe the problem is linked to Ogre being too recent?

Since I also write code, I've setup my compiler to be paranoiac (yes, this helps me spotting bugs in my own personal projects), and this conflicts with the -Werror flag being opt-out, because OD's code is far from being warning-free (C-style casts, deprecated declarations, unused constants and private members, code executed before and after main(), notably. This one is usually ignorable though, except that boot time can be interesting to optimise, but others I mentioned should be fixed) .
For info, build game me 857 warnings.

The cmake file to find CEGUI-0 is also not working when using the version provided by debian. Debian's packaged CEGUI *does* provide a .pc file (pkg-config) but not a cmake one. I'd suggest using this first, and if not found, fallback on cmake's NiH system, for several reasons:

1) pkg-config is way older
2) pkg-config is way easier to debug or write
3) I'm tempted to say it's more widely used, but I have no proof of that

Removing the requirement (seen by cmake) for Cegui, replacing it by hand-crafted values in ccmake's advanced UI and disabling -Werrors, I could have the thing to compile and link, despite warnings about conflicts between ogre and cegui.
Unfortunately, this does not executes and segfault at start. Very probably because of the hacks I had to resort to to make things compile: process does not even reachs main():

```
#0  0x00007ffff685b443 in ?? () from /usr/lib/x86_64-linux-gnu/libOgreMain.so.1.9.0
#1  0x00007ffff7fe1fe2 in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffe758, env=env@entry=0x7fffffffe768) at dl-init.c:72
#2  0x00007ffff7fe20e9 in call_init (env=0x7fffffffe768, argv=0x7fffffffe758, argc=1, l=<optimized out>) at dl-init.c:30
#3  _dl_init (main_map=0x7ffff7ffe180, argc=1, argv=0x7fffffffe758, env=0x7fffffffe768) at dl-init.c:119
#4  0x00007ffff7fd30ca in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#5  0x0000000000000001 in ?? ()
#6  0x00007fffffffea17 in ?? ()
#7  0x0000000000000000 in ?? ()
```

**Comment by ghost** [comment]
Ok, so, about the crash: no crash with 0gre 1.9, but still the hacking around cmake is required.

**Comment by tomluchowski** [comment]
I might be wrong but here's what I do : I download the ogre from here : https://www.ogre3d.org/download/sdk/sdk-ogre and I have forked cegui-0 to hack out a few settings so it applies to new Ogre enumeration: ( since some time it's 13 4 1 not 1 13 4 anymore) : https://github.com/tomluchowski/cegui/tree/v0 that's at least what I do when building my fork. First you need of course to make and make install the ogre3d then the cegui0 .....

**Comment by ghost** [comment]
In debian, I could get things working by installing those packages:

* https://packages.debian.org/bullseye/libogre-1.9-dev
* https://packages.debian.org/bullseye/libcegui-mk2-dev

and doing the build system hack, as I said. It works fine then, exept for 1 crash when leaving a game and starting a new one (100% repeat rate), and a severe memory leak that froze my game, possibly at the moment when I finished isolating my base from AI, with 0 possible entrance. Those problems are different ones though, that I might even be able to submit fixes.
